services:
  bookstore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - bookstore-network

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

volumes:
    postgres_data:
    app_data:

networks:
  bookstore-network:
    driver: bridge